TERMUX_PKG_HOMEPAGE=https://www.freebasic.net/
TERMUX_PKG_DESCRIPTION="A free BASIC compiler"
TERMUX_PKG_LICENSE="GPL-2.0"
TERMUX_PKG_MAINTAINER="@termux"
TERMUX_PKG_VERSION=1.09.0
TERMUX_PKG_SRCURL=https://github.com/freebasic/fbc/releases/download/${TERMUX_PKG_VERSION}/FreeBASIC-${TERMUX_PKG_VERSION}-source-bootstrap.tar.xz
TERMUX_PKG_SHA256=26a57c165f1c997ba7ab4c0cd9f984c752c22cd5bca434df2d8cb95c3d5549a4
TERMUX_PKG_BUILD_IN_SRC=true
#TERMUX_PKG_DEPENDS=""
TERMUX_PKG_EXTRA_MAKE_ARGS="
TARGET=$TERMUX_HOST_PLATFORM
"
